# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "48.0.2552.0";
    sha256 = "195gjdbqb14m9a6jl0ldkz6yz14m1m0rwslvfxqxx0c8x6dgk39p";
    sha256bin32 = "0f6d84apyzfwbcv0aqhvsg4ly24n5pwz8vymip5kjwwy3zzdp76s";
    sha256bin64 = "0dwwd9f9m5q598729095i4fih6j1nzbpq8mickh4c3vnxc82rd0m";
  };
  beta = {
    version = "47.0.2526.49";
    sha256 = "1p7k23bi7zhp2bz7qgddp79qfy1rwm7pkvjrzipr6qz0mc8dzb6m";
    sha256bin32 = "13l4xx8pzf743za3nb79l6qr94qyvxiprf0hx8sm6r1rqa5m7xqn";
    sha256bin64 = "1s4j40r0anjszjl0fndr208md031462zrkkzcnla8hwaq889ashk";
  };
  stable = {
    version = "46.0.2490.80";
    sha256 = "0gzy2d4x4cpd6hx9x25fwxs38y2q04afvl6rh3glzd348qli11py";
    sha256bin32 = "1cg6693x76l6y9zqadp7hwav904ryyp6bgf4xmhxk0ql5d9wsgvd";
    sha256bin64 = "11awl7nn4vxv07k0j3kxpdy9z7mwylblwlk5mb2r507nk5lsqzrh";
  };
}
