# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "49.0.2612.0";
    sha256 = "0ryyh33r4q9l1iizw1za9ki69n1va0j1c0czkh4cagyy66ww6n9q";
    sha256bin32 = "1vy6ccks9napxqkiasr72nx4wbaavfaccznp9axqvynnpcp7fis3";
    sha256bin64 = "0y5r8p71z4qfc6bmmfb2cwy05m7y16q3fx9p5zxsfz3f87dwajjd";
  };
  beta = {
    version = "48.0.2564.48";
    sha256 = "1qasdz9rwdqa2if8y4kkk19fspgjpk3q782c8l1p5n2cm25lkfa9";
    sha256bin32 = "0pgc3iy4s7whmckc14r0cvgmk7pqgidd2w0xv53bfq2k504b5ykw";
    sha256bin64 = "1lx6l8s2wdgzldbm8licpf22l6z13mvq05xlbn8ybizhn159nykj";
  };
  stable = {
    version = "47.0.2526.106";
    sha256 = "1rjqkawj7l127cd9s1wxwn4v7dfbrlahml98sam3fg8a6drm0lv4";
    sha256bin32 = "14svd5x8lzfyyigfirxx1q9pg2bsnnb0fdwa7vvh1awq3zzfd38n";
    sha256bin64 = "121289vwaz391b32hp2lihlpaql76y44gdpqkl9a3md0j1zk1nd9";
  };
}
