#!/usr/bin/env bash
if [ "$#" -le "0" ]; then
  echo "Missing filename" >&2
  exit 1
fi

SRC_DIR="$(dirname "$(readlink -f "$0")")"
VERSION="$(cat "$SRC_DIR"/default.nix | grep 'version =' | sed 's,.*version = "\(.*\)";.*,\1,')"
EXPECTED_SHA256="$(cat "$SRC_DIR"/default.nix | grep '"alpha" =' | sed 's,.*"alpha" = "\(.*\)";.*,\1,')"
THIS_SHA256="$(sha256sum "$1" | awk '{ print $1 }')"
if [ "$EXPECTED_SHA256" != "$THIS_SHA256" ]; then
  echo "SHA256 Mismatch:" >&2
  echo "  GOT:      $THIS_SHA256" >&2
  echo "  EXPECTED: $EXPECTED_SHA256" >&2
  exit 1
fi
if ! nix-prefetch-url --name "factorio-alpha-$VERSION.tar.gz" "file://$(readlink -f "$1")" >/dev/null 2>&1; then
  echo "Failed to insert tarball" >&2
  exit 1
fi
