# THIS FILE IS AUTOGENERATED, DO NOT EDIT
{ }:
{
  "stable" = {
    version = "56.0.2924.87";
    sha256 = "9aac081ffccaae6497068100477a4e6ac7086bd15ad3c3cd009b9a760b7a53e0";
  };
  "beta" = {
    version = "57.0.2987.21";
    sha256 = "632189c16d56fc23e6c3ef8174fd59ee3bae9b1c6a6740bf9a41dfb83cd39c57";
  };
  "dev" = {
    version = "57.0.2987.19";
    sha256 = "90e301e2959722e266e73ec0fd46188ebb5d512811d0b251fb6989408ca1896f";
  };
}

