# THIS FILE IS AUTOGENERATED, DO NOT EDIT
{ }:
{
  "stable" = {
    version = "56.0.2924.76";
    sha256 = "cfb08e226b9c16ad887eb96d715a9cc4ab097d1a79e2e68c8749a7a4164b3c38";
  };
  "beta" = {
    version = "56.0.2924.76";
    sha256 = "cfb08e226b9c16ad887eb96d715a9cc4ab097d1a79e2e68c8749a7a4164b3c38";
  };
  "dev" = {
    version = "57.0.2950.4";
    sha256 = "41a56ce7a89bfa0ee47039d18be1889781b78dfde88ad93ef19cabde20c5d8b6";
  };
}

