# THIS FILE IS AUTOGENERATED, DO NOT EDIT
{ }:
{
  "stable" = {
    version = "54.0.2840.71";
    sha256 = "d202d3eb0b3a979ad0e6d0d0c4faa93222c5e5b664d88b9f3a0343899fe7dd7d";
  };
  "beta" = {
    version = "55.0.2883.28";
    sha256 = "e09f3c69fc3937da9a4ef6f9dfb7eda8364bbcf17a358229ee7245544e548ae2";
  };
  "dev" = {
    version = "56.0.2902.0";
    sha256 = "88a23aea96fdec53e76cfea77c0811fc9e90dacbeb22c531af93af4d3c035ba2";
  };
}

