# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "0yaisf6gm7gg2214q4rlxav69x3br4jwf60wrgya7cgf63m61mpd";
    sha256bin64 = "05bnz5xf0kw0nrk5bmzrdzvbyh1jpxsg6frdfh1wm4p3js9wgn07";
    version = "53.0.2785.70";
  };
  dev = {
    sha256 = "0x8dw99d5884pwwjhnbxibz5j9kh7xk1ry40plqcdvsa20m7f4s8";
    sha256bin64 = "1kij7pm7zxjndgwafvc6xdp24w80kbaa422fn7pmy9ra1i05qhyf";
    version = "54.0.2837.0";
  };
  stable = {
    sha256 = "00d16yr8d9280b2rcjmjxkqvdzgy6a7l7fmnsjrj8404vcgax551";
    sha256bin64 = "0knlxgcv3wfvpgysaxb83agmp88n4ljmyx40j4r8wb5cisnl6cs8";
    version = "52.0.2743.116";
  };
}
