# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1bs0k6sqdqry2lfwsm9gncziqbz63aknvrs4v0bcrm6ccky9z1ms";
    sha256bin64 = "1n5yl2l9ic3gwqi61b6gvcd2sqy0yadpb3wvfi7g6prhsi66sg7r";
    version = "54.0.2840.16";
  };
  dev = {
    sha256 = "0nl326r1s54wnjymqj8j7rgj98klr0wdz4ffkvr839y5i0lg1kzn";
    sha256bin64 = "0ypv0yh16lkcsbdw0y5mw4g45brk84bi74n2jc9wx9cbi88ilh4j";
    version = "55.0.2859.0";
  };
  stable = {
    sha256 = "02l8z7mmk5k8j8r7wf297bb2srvysl0zsdlj156z5dg0xs1g44yq";
    sha256bin64 = "0aqg9b7y4rgwl6kpf7zklzysmz2a1laswdwnv97hpf04nv34j93j";
    version = "53.0.2785.113";
  };
}
