# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1qvx59sd0lviq19mjz40fwkvj75mmrk8xvs1wxqg2rkryxy22cdh";
    sha256bin64 = "07y9saf5clkv3as557hgadq37x2ylyj6qks4cpf9pwmhjsmd0j4c";
    version = "53.0.2785.89";
  };
  dev = {
    sha256 = "1rcbcbv53iy63b3sfg2mjv0m7fw8w9ww8affp36067av170vc7rf";
    sha256bin64 = "0d0q10nc4xywhvk9cs6r7nk4l38r5ymh7ay8q2dz20d6aii2cf81";
    version = "54.0.2840.6";
  };
  stable = {
    sha256 = "2e3c5f7b12b5b4f150b93004a718fb85778aeddc4df05bbf92b99a19a1c63dee";
    sha256bin64 = "0vbf2zc3i88cqnp0nkanyv6phqhj90p449zdqrjjfyhpjcqzci50";
    version = "53.0.2785.89";
  };
}
