# THIS FILE IS AUTOGENERATED, DO NOT EDIT
{ }:
{
  "stable" = {
    "x86_64-linux" = {
      sha256 = "51101b9aeb30eb04e09f44c2ea3ece8b8d1a735d23acff02d0ad7f77721e4e7e";
    };
  };
  "beta" = {
    "x86_64-linux" = {
      sha256 = "756487618e5312f0565f1d75b566a2319600d6aeef83734a71b99bc8faceee58";
    };
  };
  "unstable" = {
    "x86_64-linux" = {
      sha256 = "2ab54cb1588d674e9763b1c391eff7d1b09cc0fca88694bbc23bce758ceffcf9";
    };
  };
}

