# THIS FILE IS AUTOGENERATED, DO NOT EDIT
{ }:
{
  "stable" = {
    "x86_64-linux" = {
      sha256 = "124599b32e95a6f053d4a47b94768cb79b3e8ba6a6d446842af16f49ae14b2c9";
    };
  };
  "beta" = {
    "x86_64-linux" = {
      sha256 = "9c1b4830112241475ade1b80a6b8218d54fde571810840448b6afa70fed3fc6e";
    };
  };
  "unstable" = {
    "x86_64-linux" = {
      sha256 = "e896915ba36a27f1465b6c010903f00a85e5e45ce712afc4d714149881786f09";
    };
  };
}

