# THIS FILE IS AUTOGENERATED, DO NOT EDIT
{ }:
{
  "stable" = {
    "x86_64-linux" = {
      sha256 = "35acb5b5aa43947670081c666a54d414b49a7eb0d2dce0ab861637bce8eb98d6";
    };
  };
  "beta" = {
    "x86_64-linux" = {
      sha256 = "08bd4c686f34759ee25b93d39ba3c0c928708532d0ca8770d716bc007f37814d";
    };
  };
  "unstable" = {
    "x86_64-linux" = {
      sha256 = "077e3c76cd3d0d39ef4361e5644ecefc019ffc8d61f3b4f9520c6a00e6206f01";
    };
  };
}

