{ stdenv
, fetchgit
, fetchurl
, lib
, nasm

, enable10bit ? false
}:

# NOTE: the videolan autogenerated tarballs do not contain the latest sources.

let
  version = "2017-06-26";
in
stdenv.mkDerivation rec {
  name = "x264-${version}";

  src = fetchurl {
    url = "http://x264-${version}.tar.xz";
    multihash = "QmfTkaU5QeiP5jc47RTB34sakdtHEHhAEznWUfo6qeUabX";
    sha256 = "04a61a93d53476fbd21fad6dcb1271ec2b80a1ece203f120414d4588d0867d87";
  };

  nativeBuildInputs = [
    nasm
  ];

  postPatch = ''
    patchShebangs ./configure
    patchShebangs ./version.sh
  '';

  configureFlags = [
    "--enable-shared"
    "--disable-win32thread"
    "--disable-interlaced"
    "--bit-depth=${
      if enable10bit then
        "10"
      else
        "8"
    }"
    "--chroma-format=all"
    "--enable-pic"
    "--disable-avs"
    "--disable-swscale"
    "--disable-lavf"
    "--disable-ffms"
    "--disable-gpac"
    "--disable-lsmash"
  ];

  passthru = {
    generateDistTarball = stdenv.mkDerivation rec {
      name = "x264-${version}";

      src = fetchgit {
        version = 3;
        url = "https://git.videolan.org/git/x264.git";
        rev = "ba24899b0bf23345921da022f7a51e0c57dbe73d";
        sha256 = "94848774bf01b86f968f0433ba46271f000943e2bbff7f6f5c1af610114f3f13";
      };

      configurePhase = ":";

      buildPhase = ''
        tar -Jcvf x264-${version}.tar.xz ../x264*/*
      '';

      installPhase = ''
        install -D -m644 -v 'x264-${version}.tar.xz' \
          "$out/x264-${version}.tar.xz"
      '';
    };
  };

  meta = with lib; {
    description = "Library for encoding h.264/AVC video streams";
    homepage = https://www.videolan.org/developers/x264.html;
    license = licenses.gpl2;
    maintainers = [
      codyopel
    ];
    platforms = with platforms;
      x86_64-linux;
  };
}
