{ stdenv
, fetchgit
, fetchurl
, lib
, nasm
}:

# NOTE: the videolan autogenerated tarballs do not contain the latest sources.

let
  version = "2018-01-18";
in
stdenv.mkDerivation rec {
  name = "x264-${version}";

  src = fetchurl {
    url = "http://x264-${version}.tar.xz";
    multihash = "QmY7wh7RTdRHDynPq9PpNEpJdFcQf4cPnbUQSBaeJxZ4dh";
    sha256 = "9db73fdc30e88ff4ac51f6a53f06cc0f92ee4542a34c3ea7624d45a5c6d2d5c6";
  };

  nativeBuildInputs = [
    nasm
  ];

  postPatch = ''
    patchShebangs ./configure
    patchShebangs ./version.sh
  '';

  configureFlags = [
    "--enable-shared"
    "--disable-win32thread"
    "--disable-interlaced"
    "--bit-depth=all"
    "--chroma-format=all"
    "--enable-pic"
    "--disable-avs"
    "--disable-swscale"
    "--disable-lavf"
    "--disable-ffms"
    "--disable-gpac"
    "--disable-lsmash"
  ];

  passthru = {
    generateDistTarball = stdenv.mkDerivation rec {
      name = "x264-${version}";

      src = fetchgit {
        version = 5;
        url = "https://git.videolan.org/git/x264.git";
        rev = "7d0ff22e8c96de126be9d3de4952edd6d1b75a8c";
        sha256 = "db41c5a7f5730d7bfbb687204cd2aa09e6db7ef7a3acd023a467ef902cc465e1";
      };

      configurePhase = ":";

      buildPhase = ''
        tar -Jcvf x264-${version}.tar.xz ../x264*/*
      '';

      installPhase = ''
        install -D -m644 -v 'x264-${version}.tar.xz' \
          "$out/x264-${version}.tar.xz"
      '';
    };
  };

  meta = with lib; {
    description = "Library for encoding h.264/AVC video streams";
    homepage = https://www.videolan.org/developers/x264.html;
    license = licenses.gpl2;
    maintainers = [
      codyopel
    ];
    platforms = with platforms;
      x86_64-linux;
  };
}
