{ stdenv
, fetchgit
, fetchurl
, lib
, nasm
}:

# NOTE: the videolan autogenerated tarballs do not contain the latest sources.

let
  version = "2018-09-25";
in
stdenv.mkDerivation rec {
  name = "x264-${version}";

  src = fetchurl {
    url = "http://x264-${version}.tar.xz";
    multihash = "QmP94FLFCDNDBDx9SFPEgnmPQ1jKvt3hvNmFjkN2uot9Gm";
    sha256 = "a47d528a9e2e077aa820418b57c3c718d17c681fa9360e3a5526955e406ae0e5";
  };

  nativeBuildInputs = [
    nasm
  ];

  postPatch = ''
    patchShebangs configure
    patchShebangs version.sh
  '';

  configureFlags = [
    "--enable-shared"
    "--disable-win32thread"
    "--disable-interlaced"
    "--bit-depth=all"
    "--chroma-format=all"
    "--enable-pic"
    "--disable-avs"
    "--disable-swscale"
    "--disable-lavf"
    "--disable-ffms"
    "--disable-gpac"
    "--disable-lsmash"
  ];

  passthru = {
    generateDistTarball = stdenv.mkDerivation rec {
      name = "x264-${version}";

      src = fetchgit {
        version = 6;
        url = "https://git.videolan.org/git/x264.git";
        rev = "545de2ffec6ae9a80738de1b2c8cf820249a2530";
        sha256 = "e657bea1af1ac8f3747afc71838a6b3b324a6f4785eb9045ce4188b37a282cc0";
      };

      configurePhase = ":";

      buildPhase = ''
        tar -Jcvf x264-${version}.tar.xz ../x264*/*
      '';

      installPhase = ''
        install -D -m644 -v 'x264-${version}.tar.xz' \
          "$out/x264-${version}.tar.xz"
      '';
    };
  };

  meta = with lib; {
    description = "Library for encoding h.264/AVC video streams";
    homepage = https://www.videolan.org/developers/x264.html;
    license = licenses.gpl2;
    maintainers = [
      codyopel
    ];
    platforms = with platforms;
      x86_64-linux;
  };
}
