# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "49.0.2623.23";
    sha256 = "0gpzf1nrcsd2hm3yjb4ss5ym3brh20b2qb9g4sddncfpr4pq3pzn";
    sha256bin32 = "1vvwkyi5im060fswibfd5n7f4b2k9z8vhhb3bqxg6lhd5jwr96mf";
    sha256bin64 = "0zbgjx2k1q7kn5a7sw1l2527xw33ngaffakkfiajfx45lazmp48g";
  };
  beta = {
    version = "49.0.2623.28";
    sha256 = "1cpgfcw6kgw70k14wa1m5qzj4rnvkzrw1am30d34516mbwlmmqc8";
    sha256bin32 = "0nwhjav1x325h1drqknrjl5glivn4fdpahs1nlaqfk8kbjh1q113";
    sha256bin64 = "0wj6j0v3rngsclzbb8rc8l90wdi98j2sb60r2ypfihaxq2gd138y";
  };
  stable = {
    version = "48.0.2564.97";
    sha256 = "1nsjn8zlqljizy5dmg2rxwkw4k5j4yi15ywxi9ca3acv68dbhd3p";
    sha256bin32 = "0gdd9krsfsixw5b03msm7nf7zl7xh4chzkh9srb19c1kzygl2j2l";
    sha256bin64 = "1wmw17gdq1j6vxfdc8s94jc8z30pza8nipk4dh590xnb7faihr52";
  };
}
