# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "49.0.2618.8";
    sha256 = "1vbw8smf0qi8f1qnrzni8n3b6x7mq1kcbm21v588d470qqa7xsrn";
    sha256bin32 = "1gzhqj0d23drw0dl8vrp0yc28z8fivjznr46iv040hb8nz4ny0l9";
    sha256bin64 = "1allwpxms5zdkl18340jjxisn020iniybph9k33kz38fga1h2aan";
  };
  beta = {
    version = "48.0.2564.79";
    sha256 = "127pzqy1r1wxwwjgadach20knh3wxzg46w9hxy3f7ml05nrbm0fl";
    sha256bin32 = "0qlxjglln1hhrjdh1kacadkx34p4x0xjajcz7mwm3c3br7wwmbcf";
    sha256bin64 = "1vayqv3vw2d86waywyk6jc6n0wbq11m2b8x8yis05rk8sj909hba";
  };
  stable = {
    version = "47.0.2526.111";
    sha256 = "021p16z7vav828k5gy3z8cai0n68kd1gna2pih3l9csfcf4r36hp";
    sha256bin32 = "0iylyrzwlj680dplxni2m57xqdn83q42g2q8dji8pjbx8ygjn697";
    sha256bin64 = "0510q0j8kkahmag5isrniwzigjbn93malzgjx898ppj04jjg9w60";
  };
}
