# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "49.0.2623.13";
    sha256 = "0nz24lh2fa5vn43q5gagcqg3mingx5nkalfk0a0ygzx2mv8f4pcw";
    sha256bin32 = "0kdms5b1bnnnx1afzq27wcvxg2wadsphncapzr0j1n2cy95n0z00";
    sha256bin64 = "1nxq1mdnlk6vkhphm95ypk06lz9lwf3z3qf4v1bzjjcvp81fkrz7";
  };
  beta = {
    version = "48.0.2564.82";
    sha256 = "1z8l2wzgsap4a9vprh4f4dv3393zrpni4f468mysw6yh4zs4p9nd";
    sha256bin32 = "0bh2hv2mdsx3x1jjpysfz8h52s2wd01vijwb7902zz31jz7spz07";
    sha256bin64 = "0963hnj1br03zsjl6188nifdxacm55h9x2222s994hss540q9wha";
  };
  stable = {
    version = "48.0.2564.82";
    sha256 = "1z8l2wzgsap4a9vprh4f4dv3393zrpni4f468mysw6yh4zs4p9nd";
    sha256bin32 = "0sk0clhkrbvnnwc74hnsy872hkabsb9wfzfs4jzi4yqfwb9ca92x";
    sha256bin64 = "0ds6z1ll3s6d9wmz03wdzi560fyzs4aqi9cw7x2zkgnghx078ris";
  };
}
