# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "10d83qn835m78wg7ai35g0z8rjfhy4amni4835q5ynrrlcni3sp6";
    sha256bin64 = "15501nlix0pn0gwcw7l8jlq0137xlf1x44hn34r06fqf72wps1gg";
    version = "52.0.2743.49";
  };
  dev = {
    sha256 = "1b10zngiqsyy828a8c3rm6j5fhrd4iqjp8spgfh14b4xf0vbnh62";
    sha256bin64 = "10hr07mpscpin5jrq841sqyjbvalyxnjf9wzi27n1r5sl3q1a6i1";
    version = "53.0.2774.3";
  };
  stable = {
    sha256 = "0aypf5lhi2l7cn41xhq2ck6bjblapwv26nygvg2883hhqinmnwvn";
    sha256bin64 = "1c1796sd82l480xjdw7w46867w2phw3ng2dvdb6njsvpg299chi8";
    version = "51.0.2704.103";
  };
}
