# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1iw1blj3vdcsfjzhbhw44iyfvzjrr5v09l0vy9cwzl7msdy2ckdf";
    sha256bin64 = "01pyp3nqcdmc2c7jcf0csmrgnn9nwnx3znk270czschf861lm1n4";
    version = "51.0.2704.29";
  };
  dev = {
    sha256 = "1zjmaz9iz8gbvwzk8in8d2ic9q7s2vy5nwl1634sirzw82k97xf0";
    sha256bin64 = "1m5ll9ma7kvw00cskk7xn51yhjiqfcx3xpiaxkald5g9zzsknj5l";
    version = "52.0.2716.0";
  };
  stable = {
    sha256 = "06dsdlc0p3nsxhpwpcbr66brijq42gryp92z1bqb6hkd0xmm3w36";
    sha256bin64 = "1pfv6h8lixrqsrgwxi4bcdbpyc4xa9gvhmi2jfnp2045nfg360rq";
    version = "50.0.2661.94";
  };
}
