# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "15m949ckx7vyz69xc0ls51vlns9nsih43sg9srd2kxf6w75diq6c";
    sha256bin64 = "1rv146vnn1w0543q559dyjfpy1psjpdm9rfcqsg2z2wvh5ywvwav";
    version = "50.0.2661.66";
  };
  dev = {
    sha256 = "1w5sk77984r69ysp5d8wi6m18w6arjc6nzqhzda6c694mqlfwhjr";
    sha256bin64 = "18hsicf1h1jcjnklsfdpdnda7bg6awr8wx39inhgj4y4613iwpk5";
    version = "51.0.2700.0";
  };
  stable = {
    sha256 = "1lmv6nmbqhxmr4340s5i4ypgz2b7vkh0wy5x9v75b5bnscjhk121";
    sha256bin64 = "1djd2i9phym1d8afv4vfajb7l1bz0ny2wmihwi6jaz712vil4a13";
    version = "49.0.2623.110";
  };
}
